
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: yannick
  password:  <%= ENV['MYFIRSTRUBYAPP_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: myfirstrubyapp_development
  password: <%= ENV['MYFIRSTRUBYAPP_DATABASE_PASSWORD'] %>


test:
  <<: *default
  database: myfirstrubyapp_test

production:
  <<: *default
  database: myfirstrubyapp_production
  password: <%= ENV['MYFIRSTRUBYAPP_DATABASE_PASSWORD'] %>